apiVersion: infrastructure.flintlock.x-k8s.io/v1alpha1
kind: Microvm
metadata:
  labels:
    app.kubernetes.io/name: microvm
    app.kubernetes.io/instance: microvm-sample
    app.kubernetes.io/part-of: microvm-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: microvm-operator
  name: microvm-sample
spec:
  host:
    name: host1
    endpoint: 1.2.3.4:9090
  sshPublicKeys:
  - user: "root"
    authorizedKeys:
    - "ssh-ed25519 foobar"
  userdata: |
    #!/bin/bash
    echo "hi from my microvm!"
  kernel:
    filename: boot/vmlinux
    image: ghcr.io/weaveworks-liquidmetal/flintlock-kernel:5.10.77
  kernelCmdline: {}
  memoryMb: 2048
  vcpu: 2
  networkInterfaces:
  - guestDeviceName: eth1
    type: macvtap
  rootVolume:
    id: root
    image: ghcr.io/weaveworks-liquidmetal/capmvm-kubernetes:1.21.8
